=== rene-anderes/edu/xml/src/main/resources/org/anderes/edu/xml/xpath/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="CATALOG">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PLANT" type="PLANT" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="PLANT">
		<xs:sequence>
			<xs:element name="COMMON" type="xs:string"/>
			<xs:element name="BOTANICAL" type="xs:string"/>
			<xs:element name="ZONE" type="xs:string"/>
			<xs:element name="LIGHT" type="xs:string"/>
			<xs:element name="CHARACTERISTICS" type="CHARACTERISTICS" minOccurs="0"/>
			<xs:element name="BUSINESS" type="BUSINESS"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PRICE">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="currency" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="USD"/>
							<xs:enumeration value="EUR"/>
							<xs:enumeration value="CHF"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="BUSINESS">
		<xs:sequence>
			<xs:element name="PRICE" type="PRICE"/>
			<xs:element name="AVAILABILITY" type="xs:int"/>
			<xs:element name="COMMENT" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="DE"/>
							<xs:enumeration value="EN"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== rene-anderes/edu/xml/src/main/resources/org/anderes/edu/xml/xpath/plants.xml
<?xml version="1.0" encoding="UTF-8"?>
<CATALOG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plants.xsd">
	<PLANT>
		<COMMON>Bloodroot</COMMON>
		<BOTANICAL>Sanguinaria canadensis</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">2.44</PRICE>
			<AVAILABILITY>031599</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Columbine</COMMON>
		<BOTANICAL>Aquilegia canadensis</BOTANICAL>
		<ZONE>3</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.37</PRICE>
			<AVAILABILITY>030699</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Marsh Marigold</COMMON>
		<BOTANICAL>Caltha palustris</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Mostly Sunny</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">6.81</PRICE>
			<AVAILABILITY>051799</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Cowslip</COMMON>
		<BOTANICAL>Caltha palustris</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<CHARACTERISTICS language="EN">Caltha palustris, commonly called marsh marigold, is a rhizomatous perennial that in North America is native to marshes, swamps, wet meadows and stream margins from Newfoundland to Alaska south to Nebraska, Tennessee and North Carolina.</CHARACTERISTICS>
		<BUSINESS>
			<PRICE currency="USD">9.90</PRICE>
			<AVAILABILITY>030699</AVAILABILITY>
			<COMMENT>not always available</COMMENT>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Dutchman's-Breeches</COMMON>
		<BOTANICAL>Dicentra cucullaria</BOTANICAL>
		<ZONE>3</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">6.44</PRICE>
			<AVAILABILITY>012099</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Ginger, Wild</COMMON>
		<BOTANICAL>Asarum canadense</BOTANICAL>
		<ZONE>3</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.03</PRICE>
			<AVAILABILITY>041899</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Hepatica</COMMON>
		<BOTANICAL>Hepatica americana</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">4.45</PRICE>
			<AVAILABILITY>012699</AVAILABILITY>
			<COMMENT>check availability</COMMENT>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Liverleaf</COMMON>
		<BOTANICAL>Hepatica americana</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">3.99</PRICE>
			<AVAILABILITY>010299</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Jack-In-The-Pulpit</COMMON>
		<BOTANICAL>Arisaema triphyllum</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<CHARACTERISTICS language="EN">One to two large, glossy leaves, divided into three leaflets, rise on their own stems 1-3 ft. The intriguing blossom of this woodland perennial occurs on a separate stalk at the same height as the leaves. It is a large, cylindrical, hooded flower, green in color with brown stripes. Distinctive Jack-in-the-pulpit formation grows beneath large leaves. In late summer, a cluster of bright red berries appears.</CHARACTERISTICS>
		<BUSINESS>
			<PRICE currency="USD">3.23</PRICE>
			<AVAILABILITY>020199</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Mayapple</COMMON>
		<BOTANICAL>Podophyllum peltatum</BOTANICAL>
		<ZONE>3</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">2.98</PRICE>
			<AVAILABILITY>060599</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Phlox, Woodland</COMMON>
		<BOTANICAL>Phlox divaricata</BOTANICAL>
		<ZONE>3</ZONE>
		<LIGHT>Sun or Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">2.80</PRICE>
			<AVAILABILITY>012299</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Phlox, Blue</COMMON>
		<BOTANICAL>Phlox divaricata</BOTANICAL>
		<ZONE>3</ZONE>
		<LIGHT>Sun or Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">5.59</PRICE>
			<AVAILABILITY>021699</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Spring-Beauty</COMMON>
		<BOTANICAL>Claytonia Virginica</BOTANICAL>
		<ZONE>7</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<CHARACTERISTICS language="EN">Springbeauty is a perennial plant, overwintering through a corm. It is a trailing plant growing to 5–40 cm long. The leaves are slender lanceolate, 3–14 cm long and 0.5–1.3 cm broad, with a 6–20 cm long petiole.</CHARACTERISTICS>
		<BUSINESS>
			<PRICE currency="USD">6.59</PRICE>
			<AVAILABILITY>020199</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Trillium</COMMON>
		<BOTANICAL>Trillium grandiflorum</BOTANICAL>
		<ZONE>5</ZONE>
		<LIGHT>Sun or Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">3.90</PRICE>
			<AVAILABILITY>042999</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Wake Robin</COMMON>
		<BOTANICAL>Trillium grandiflorum</BOTANICAL>
		<ZONE>5</ZONE>
		<LIGHT>Sun or Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">3.20</PRICE>
			<AVAILABILITY>022199</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Violet, Dog-Tooth</COMMON>
		<BOTANICAL>Erythronium americanum</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.04</PRICE>
			<AVAILABILITY>020199</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Trout Lily</COMMON>
		<BOTANICAL>Erythronium americanum</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">6.94</PRICE>
			<AVAILABILITY>032499</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Adder's-Tongue</COMMON>
		<BOTANICAL>Erythronium americanum</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.58</PRICE>
			<AVAILABILITY>041399</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Anemone</COMMON>
		<BOTANICAL>Anemone blanda</BOTANICAL>
		<ZONE>6</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<CHARACTERISTICS language="DE">Die Windröschen (Anemone) bilden eine Pflanzengattung in der Familie der Hahnenfußgewächse (Ranunculaceae). Zu dieser Gattung zählen rund 150 Arten, die vor allem auf der Nordhalbkugel und dort schwerpunktmässig in den gemässigten Zonen Asiens heimisch sind.</CHARACTERISTICS>
		<BUSINESS>
			<PRICE currency="USD">8.86</PRICE>
			<AVAILABILITY>122698</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Grecian Windflower</COMMON>
		<BOTANICAL>Anemone blanda</BOTANICAL>
		<ZONE>6</ZONE>
		<LIGHT>Mostly Shady</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.16</PRICE>
			<AVAILABILITY>071099</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Bee Balm</COMMON>
		<BOTANICAL>Monarda didyma</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">4.59</PRICE>
			<AVAILABILITY>050399</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Bergamot</COMMON>
		<BOTANICAL>Monarda didyma</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">7.16</PRICE>
			<AVAILABILITY>042799</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Black-Eyed Susan</COMMON>
		<BOTANICAL>Rudbeckia hirta</BOTANICAL>
		<ZONE>Annual</ZONE>
		<LIGHT>Sunny</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.80</PRICE>
			<AVAILABILITY>061899</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Buttercup</COMMON>
		<BOTANICAL>Ranunculus</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">2.57</PRICE>
			<AVAILABILITY>061099</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Crowfoot</COMMON>
		<BOTANICAL>Ranunculus</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.34</PRICE>
			<AVAILABILITY>040399</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Butterfly Weed</COMMON>
		<BOTANICAL>Asclepias tuberosa</BOTANICAL>
		<ZONE>Annual</ZONE>
		<LIGHT>Sunny</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">2.78</PRICE>
			<AVAILABILITY>063099</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Cinquefoil</COMMON>
		<BOTANICAL>Potentilla</BOTANICAL>
		<ZONE>Annual</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">7.06</PRICE>
			<AVAILABILITY>052599</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Primrose</COMMON>
		<BOTANICAL>Oenothera</BOTANICAL>
		<ZONE>3 - 5</ZONE>
		<LIGHT>Sunny</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">6.56</PRICE>
			<AVAILABILITY>013099</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Gentian</COMMON>
		<BOTANICAL>Gentiana</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Sun or Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">7.81</PRICE>
			<AVAILABILITY>051899</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Blue Gentian</COMMON>
		<BOTANICAL>Gentiana</BOTANICAL>
		<ZONE>4</ZONE>
		<LIGHT>Sun or Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">8.56</PRICE>
			<AVAILABILITY>050299</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Jacob's Ladder</COMMON>
		<BOTANICAL>Polemonium caeruleum</BOTANICAL>
		<ZONE>Annual</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">9.26</PRICE>
			<AVAILABILITY>022199</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>Greek Valerian</COMMON>
		<BOTANICAL>Polemonium caeruleum</BOTANICAL>
		<ZONE>Annual</ZONE>
		<LIGHT>Shade</LIGHT>
		<BUSINESS>
			<PRICE currency="USD">4.36</PRICE>
			<AVAILABILITY>071499</AVAILABILITY>
		</BUSINESS>
	</PLANT>
	<PLANT>
		<COMMON>California Poppy</COMMON>
		<BOTANICAL>Eschscholzia californica</BOTANICAL>
		<ZONE>Annual</ZONE>
		<LIGHT>Sun</LIGHT>
